version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "999:999"

  api-services:
    container_name: api-services
    restart: always
    build: ./Api-services
    ports:
      - "8002:8002"

  auth:
    container_name: auth
    restart: always
    build: ./Auth
    ports:
      - "8001:8001"

  database:
    container_name: database
    restart: always
    build: ./DB
    ports:
      - "8000:8000"
