### insert new Movie
POST http://localhost:8000/Movie
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZyYW5zeHBvbnRvbnNzc0BnbWFpbC5jb20iLCJpYXQiOjE2ODU2NDc5OTksImV4cCI6MTY4NTY1MTU5OX0.VzJFoLWoNtixbeEbULLCvspHxUZm4BKfSIk7zSNOE-Y

{
    "title":"figth club",
    "release":"2019",
    "language":"Eng",
    "genres":["Thriller","Suspence"], 
    "actors": "6478efc01a9de92edc4e2896"
}



### get films
GET http://localhost:8000/Movie
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZyYW5zeHBvbnRvbnNzc0BnbWFpbC5jb20iLCJpYXQiOjE2ODU2NTg5NzgsImV4cCI6MTY4NTY2MjU3OH0.MjB3T2O4MMvLfMsdwAOlsvWxn5cD4BRY1HBDtvInWAY


