### insert new Movie
POST http://localhost:8000/TvShow
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2E0NWI3ZGQ3ODEwNjIzYzhmNjcwYSIsIm5hbWUiOiJ7ZnN0dHRkZHN9IiwiZW1haWwiOiJmcmFuY2lzY28uc3BvbnRvbkBnbWFpbC5jb20iLCJpYXQiOjE2ODU5NzY0OTIsImV4cCI6MTY4NTk4MDA5Mn0.89-fE3-GdB_KPtLSCThlL9O61OfrDbuSSWJKUZWUybg

{
   "title": "show match", 
   "release": "1990",
   "language":"SPA",
   "genres":["Comedy"],
   "seasons": 10
}



### Get all tvshows
GET http://localhost:8000/TvShow
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2E0NWI3ZGQ3ODEwNjIzYzhmNjcwYSIsIm5hbWUiOiJ7ZnN0dHRkZHN9IiwiZW1haWwiOiJmcmFuY2lzY28uc3BvbnRvbkBnbWFpbC5jb20iLCJpYXQiOjE2ODU5NzY0OTIsImV4cCI6MTY4NTk4MDA5Mn0.89-fE3-GdB_KPtLSCThlL9O61OfrDbuSSWJKUZWUybg

### Get tvshow by id
GET http://localhost:8000/TvShow?id=647df5d82eea3635a8a5ab09
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2E0NWI3ZGQ3ODEwNjIzYzhmNjcwYSIsIm5hbWUiOiJ7ZnN0dHRkZHN9IiwiZW1haWwiOiJmcmFuY2lzY28uc3BvbnRvbkBnbWFpbC5jb20iLCJpYXQiOjE2ODU5NzY0OTIsImV4cCI6MTY4NTk4MDA5Mn0.89-fE3-GdB_KPtLSCThlL9O61OfrDbuSSWJKUZWUybg



### Sort by prop, asc or desc
GET http://localhost:8000/TvShow/sort?prop=release&shape=1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0N2E0NWI3ZGQ3ODEwNjIzYzhmNjcwYSIsIm5hbWUiOiJ7ZnN0dHRkZHN9IiwiZW1haWwiOiJmcmFuY2lzY28uc3BvbnRvbkBnbWFpbC5jb20iLCJpYXQiOjE2ODU5NzY0OTIsImV4cCI6MTY4NTk4MDA5Mn0.89-fE3-GdB_KPtLSCThlL9O61OfrDbuSSWJKUZWUybg
