#### Register User
POST http://localhost:8000/User/register
Content-Type: application/json

{
    "name":"fs",
    "email":"FRANSxPontonsss@gmail.com ",
    "password":"123456"
}


#### Login user - Return token
POST http://localhost:8000/User/login
Content-Type: application/json

{
    "email":"FRANSxPontonsss@gmail.com ",
    "password":"123456"
}


####