#### Register User
POST http://localhost:8000/User/register
Content-Type: application/json  

{
    "name":"seba",
    "email":" seba@gmail.com ",
    "password":"123456",
    "gender":"Male"
}


#### POST - Login user - Return token for requests
POST http://localhost:8000/User/login
Content-Type: application/json

{
    "email":" seba@gmail.com  ",
    "password":"123456"
}


#### GET LIST OF USERS
GET  http://localhost:8000/User
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoie2ZzdHR0ZGRzfSIsImVtYWlsIjoiZnNzZHNhYWFhYWFhYWFhYWFhYWFzYWFhYWFhc3NhYWFzc3Nzc3Nzc3NhYWFzYWFhYWFhc2FhYWFhYXN0dHRAZ21haWwuY29tIiwiaWF0IjoxNjg1NzIxODA2LCJleHAiOjE2ODU3MjU0MDZ9._40n6diXKQydUK4Z_09JRWSUhHzHOX5O3MmCvJ0WWzw

